services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
#    networks:
#      - dac-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/dac
#      SPRING_DATASOURCE_USERNAME: dac
#      SPRING_DATASOURCE_PASSWORD: dac
#      SPRING_JPA_HIBERNATE_DDL_AUTO: create
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=dac
      - POSTGRES_USER=dac
      - POSTGRES_DB=dac
#    networks:
#      - dac-network
    ports:
      - "5432:5432"
#
#networks:
#  dac-network:
#    driver: bridge