server:
  port: 8081

spring:
  application:
    name: emailService

  mail:
    host: smtp.gmail.com
    port: 587
    username: 'aksdaksda'
    password: 'dsfsdfsdf'
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 50000
          timeout: 50000
          writetimeout: 50000

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: ticketExchange
    queues:
      email-notification: email-notification-request-queue
    routing-keys:
      send-email: email-notification-request

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
