rabbitmq:
  queue: email-request-queue
  error-queue: email-response-error-queue
  success-queue: email-response-success-queue
  exchange: email-exchange
  routing-key:
    response-error: email-response-error
    response-success: email-response-success


spring:
  application:
    name: emailService

  rabbitmq:
    host: localhost
    port: 5672
    username: dac
    password: dac

  mail:
    host: smtp.gmail.com
    port: 587
    username: 'aksdaksda'
    password: 'dsfsdfsdf'
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 50000
          timeout: 50000
          writetimeout: 50000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
