rabbitmq:
  queue: email-queue
  exchange: email-exchange
  routing key: email-request

spring:
  application:
    name: emailService
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1  # Limits messages per consumer to avoid overload
        acknowledge-mode: manual  # Enables manual acknowledgment

  mail:
    host: smtp.gmail.com
    port: 587
    username: 'aksdaksda'
    password: 'dsfsdfsdf'
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 50000
          timeout: 50000
          writetimeout: 50000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
